### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by carsonsaldanha** [google/monster-mash#8]
[https://monstermash.zone](https://monstermash.zone) doesn't work

**Comment by micwoj92** [comment]
What do you mean "it should" how does this even have any relation for the code in this repo? Have you tried testing the web app on your local web server with https?

**Comment by carsonsaldanha** [comment]
Seems fixed!

**Comment by micwoj92** [comment]
See? None of the code in this repo was changed, I was right.
